### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by glorialee820**
added an image for readme

### CODE REVIEW

**Review by lfeldman — COMMENTED** [review]
Which version of the image is proper? Image.png or stack_image.png?

**Review by lfeldman — CHANGES_REQUESTED** [review]
@glorialee820 I have started the tests of your code and I don't know what should be placed as value for gromacs_binaries. I have been hit by this problem when terraform plan has been executed:

```
dhcp-10-175-223-164:oci-hpc-runbook-gromacs lukaszfeldman$ terraform plan
var.gromacs_binaries
  Enter a value:
```
Please update the README with the information needed.

**Review by lfeldman — CHANGES_REQUESTED** [review]
Please return to original content of the provider.tf. In current version provider block is commented out. It should look like this:

```
## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
}

provider "oci" {
  alias                = "homeregion"
  tenancy_ocid         = var.tenancy_ocid
  user_ocid            = var.user_ocid
  fingerprint          = var.fingerprint
  private_key_path     = var.private_key_path
  region               = data.oci_identity_region_subscriptions.home_region_subscriptions.region_subscriptions[0].region_name
  disable_auto_retries = "true"
} 
```

**Review by lfeldman — CHANGES_REQUESTED** [review]
You should re-enter the declarations of `fingerprint`,` user_ocid`, `private_key_path` variables in variables.tf file. Otherwise, I will not overcome the error I am now experiencing: 

image

**Review by lfeldman — CHANGES_REQUESTED** [review]
@glorialee820 the issue lays in [variables.tf](https://github.com/oracle-quickstart/oci-hpc-runbook-gromacs/blob/dev/variables.tf). Please verify the content of it. It looks like you have to change the variables (remove `api_` prefix):

```
variable "api_user_key"  => "private_key_path"
variable "api_fingerprint" => "fingerprint"
variable "api_user_ocid" => "user_ocid"
```

**Review by lfeldman — CHANGES_REQUESTED** [review]
During the last test it has failed on the usage of Flex shapes as follows:
image

**Review by lfeldman — CHANGES_REQUESTED** [review]
Changing default to `BM.GPU3.8` doesn't fix the issue:

image

**Review by lfeldman — COMMENTED** [review]
I have added my changes and my first try with Terraform CLI was successful:
image
I will try to test it with the Resource Manager.

**Review by lfeldman — CHANGES_REQUESTED** [review]
During the tests with ORM/RMS I am facing this issue every time. Please consider the refresh of the Ansible code to eliminate this issue. Otherwise, the stack is broken:
image

**Comment by glorialee820** [comment]
It may be a one time issue, can you please try again, I was successful in my tenancy.

**Comment by lfeldman** [comment]
@glorialee820 I have had the issue a few times. I will send you ORM/RMS stack in a form of a zip file. Please try it at your end.

**Comment by glorialee820** [comment]
it was successful in my tenancy
[](url)
[ocid1.ormjob.oc1.ap-osaka-1.aaaaaaaa3e4apccbhdt4zv4k7as6lxef6jglknqtgw57azpuodi7elyf3voq.log](https://github.com/oracle-quickstart/oci-hpc-runbook-gromacs/files/7864373/ocid1.ormjob.oc1.ap-osaka-1.aaaaaaaa3e4apccbhdt4zv4k7as6lxef6jglknqtgw57azpuodi7elyf3voq.log)

**Review by lfeldman — APPROVED** [review]

**Pull request merged**
